### ISSUE TITLE
Can not open phar file

### ISSUE THREAD

**Issue by Anongh** [cweiske/phancap#2]
The phar file can not be opened in my web browser with the following error.
"Fatal error: Class 'phancap \ Options' not found in phar: //~/phancap-0.4.0.phar/www/index.php on line 25"

I think it's a conflict based on the namespace convention between psr-0 and psr-4.

Is there any way to bypass?

**Comment by cweiske** [comment]
Did you copy that error message or type it yourself? There are spaces before and after the `\` which should not be there.

Also: Which PHP version, which web server and which version do you use?

**Comment by Anongh** [comment]
Oh, sorry.

There is no space.
Just "Fatal error: Class 'phancap\Options' not found in ~~~".

My php version is PHP 5.6.30 and runs Apache v2.4.23 on Windows.

**Comment by cweiske** [comment]
Sorry, I have no idea how and why this should occur.

You could try to use the git checkout and install the necessary depdencies.
