### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by olpo24** [cweiske/phancap#3]
Nach öffnen der phar Datei im Browser bekomme ich gleich einen HTTP Error 500.

Irgendwelche Ideen? Apache Error Log sagt nix.

**Comment by cweiske** [comment]
In der `php.ini` folgendes aktivieren, dann apache (oder den fpm-daemon) neustarten:

- log_errors=On
- error_log=/var/log/php-errors.log
- display_errors=On
- display_startup_errors=On

**Comment by olpo24** [comment]
Danke.

Dann kommt golgendes:

Warning: include(): Failed opening 'phancap/Options.php' for inclusion (include_path='phar:///home/www/screen/phancap.phar:phar:///home/www/screen/phancap.phar/lib/:phar:///home/www/screen/phancap.phar/src/phancap/../') in phar:///home/www/screen/phancap.phar/src/phancap/Autoloader.php on line 40

Fatal error: Uncaught Error: Class 'phancap\Options' not found in phar:///home/www/screen/phancap.phar/www/index.php:25 Stack trace: #0 [internal function]: unknown() #1 /home/www/screen/phancap.phar(56): Phar::webPhar(NULL, 'www/index.php', '', Array, 'rewritePath') #2 {main} thrown in phar:///home/www/screen/phancap.phar/www/index.php on line 25

**Comment by cweiske** [comment]
Stale.
